(define (partial-sums stream)
  (define (helper start stream)
    (if (null? stream) nil
        (let ((start (+ start (car stream))))
          (cons-stream start (helper start (cdr-stream stream)))
        )
    )
  )
  (helper 0 stream)
)
